services:
  backend:
    build:
      context: ./calling-backend
      dockerfile: Dockerfile
    container_name: in-backend
    ports:
      - "3008:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://rootuser:ro23ifno3inFEf@mongodb:27017/calling?authSource=admin
      - PORT=3000
    depends_on:
      - mongodb
    # volumes:
    #   - ./backend/contacts_mokeb.xlsx:/app/contacts_mokeb.xlsx
    networks:
      - in-network

  mongodb:
    image: mongo:latest
    container_name: inmongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=ro23ifno3inFEf
      - MONGO_INITDB_DATABASE=calling
    volumes:
      - ./data/mongo-data:/data/db
    networks:
      - in-network

  front:
    container_name: in-frontend
    working_dir: /app
    build:
      context: ./calling-frontend
      dockerfile: Dockerfile
    ports:
      - "3006:80"
    # environment:
    #   - NODE_ENV=production
    #   - VITE_SERVER=https://callapi.mostadrak.com
    depends_on:
      - backend
    networks:
      - in-network

  admin:
    container_name: in-admin
    build:
      context: ./calling-admin
      dockerfile: Dockerfile
    ports:
      - "3007:3000"
    # environment:
    #   - NODE_ENV=production
    #   - NEXT_PUBLIC_SERVER=https://callapi.mostadrak.com
    #   - NEXT_PUBLIC_USERNAME=admin
    #   - NEXT_PUBLIC_PASSWORD=110110
    depends_on:
      - backend
    networks:
      - in-network

#  nginx:
#    image: nginx
#    container_name: in-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./conf:/etc/nginx/conf.d
#    depends_on:
#      - backend
#      - admin
#      - front
#    networks:
#      - in-network

networks:
  in-network:
    driver: bridge
