services:
  backend:
    build:
      context: ./calling-backend
      dockerfile: Dockerfile
    container_name: in-backend
    ports:
      - "3008:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://rootuser:ro23ifno3inFEf@mongodb:27017/calling?authSource=admin
      - PORT=3000
    depends_on:
      - mongodb
    # volumes:
    #   - ./backend/contacts_mokeb.xlsx:/app/contacts_mokeb.xlsx
    networks:
      - in-network

  mongodb:
    image: mongo:latest
    container_name: inmongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=ro23ifno3inFEf
      - MONGO_INITDB_DATABASE=calling
    volumes:
      - ./data/mongo-data:/data/db
    networks:
      - in-network

networks:
  in-network:
    driver: bridge
